# 默认使用配置
spring:
  profiles:
    active: dev
# 公共配置与profiles选择无关
mybatis:
  type-aliases-package: cn.sitedev.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---

# 开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/sitedev-mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver